[phases.setup]
nixPkgs = ["nodejs_20", "npm"]

[phases.install]
cmds = [
  "rm -f package-lock.json || true",
  "npm config set package-lock false",
  "npm config set prefer-offline false",
  "npm install --no-package-lock --legacy-peer-deps"
]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "npx serve -s dist -l $PORT"

