// build-api.mjs - Build script for Vercel Serverless Functions
import { build } from 'esbuild';
import { fileURLToPath } from 'url';
import { dirname, join } from 'path';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

console.log('🔨 Building Vercel Serverless Functions...');

try {
  // Build the tRPC API handler
  await build({
    entryPoints: [join(__dirname, 'api', 'trpc.ts')],
    bundle: true,
    platform: 'node',
    target: 'node18',
    format: 'esm',
    outfile: join(__dirname, 'api', 'trpc.js'),
    external: [
      // Keep these as external to use Vercel's versions
      '@vercel/node',
      'postgres',
      'mysql2',
      'bcrypt',
      'bcryptjs',
    ],
    minify: false,
    sourcemap: true,
    metafile: true,
    logLevel: 'info',
    banner: {
      js: '// Auto-generated by build-api.mjs - DO NOT EDIT MANUALLY',
    },
  });

  console.log('✅ Build completed successfully!');
  console.log('📦 Output: api/trpc.js');
  
} catch (error) {
  console.error('❌ Build failed:', error);
  process.exit(1);
}
